# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a95e26551034d5f2d2ae7aca9756d71e868e135b93eab122bf831f8d2b3a462d0dd87c9f86d8d1fac35510c41ab644332415a4fb211b2f72ee9bb357a583aec

test:
  secret_key_base: 9c336b4d211073b9c2afd6822bd902ba8e00006412b0f7dc70ae494ec589b19203d01c015ff9d898229730fc43810fa9c7e4a8787f37353a3093cd43f205b022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
